{
 "title": "PiGrowSoft Beta",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Water Capacitance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gauge_moisture_capacitance{service=\"pi_grow_soft\"}"
    }
   ]
  },
  {
   "title": "Air Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "gauge_air_temperature" }
   ]
  },
  {
   "title": "Lights",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "gauge_relay_light_state{service=\"pi_grow_soft\"}"
    }
   ]
  }
 ]
}