relay:
  1: 5
  2: 6
thSensor:
  enabled: true
  pin: 4
# 1602 Display Config
#display:
#  enabled: false
#  type: lcd1602
#  connectionInfo:
#    rs: 17
#    e: 27
#    pins: [13, 6, 5, 22]
#    width: 16
devices:
  lights:
    enabled: true
    relay: 2
    onTime: 6:00AM
    duration: 18h
  fans:
    enabled: true
    relay: 1
    triggerTempCelsius: 27
moistureSensor:
  enabled: true
  lowRange: 400
moistureSensors:
  1:
    type:
    enabled: true
    address: 0x36
    lowRange: 400
  2:
    enabled: true
    address: 0x36
    lowRange: 400
  3:
    enabled: true
    address: 0x38
    lowRange: 400
  defaultLowRange: 400
metrics:
