relay:
  1: 6
  2: 5
thSensor:
  enabled: true
  pin: 4
# 1602 Display Config
#display:
#  enabled: false
#  type: lcd1602
#  connectionInfo:
#    rs: 17
#    e: 27
#    pins: [13, 6, 5, 22]
#    width: 16
devices:
  lights:
    enabled: true
    relay: 2
    onTime: 12:00PM
    duration: 1m
  fans:
    enabled: true
    relay: 1
    triggerTempCelsius: 27
moistureSensor:
  enabled: true
  lowRange: 400
metrics:
